Algoritmo "semnome"

Var

   x,y,soma,diferenca,produto,media:real
Inicio

      escreva("Digite um número:")
        leia (x)
      escreva("Digite um número:")
        leia (y)
        
      soma<-(x+y)
      escreval("Resultado da soma:",soma)
      media<-(soma)/2
      escreval("Resultado média",media)
      diferenca<-(x-y)
      escreval("Resultado diferença:",diferenca)
      produto<-(x*y)
      escreval("Resultado produto:",produto)

Fimalgoritmo